//
//  FlutterBridgeModule.m
//  Appspensive
//
//  Auto-generated by withFlutterBridge plugin
//

#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(FlutterBridgeModule, NSObject)

RCT_EXTERN_METHOD(openFlutter:(NSString *)route params:(NSDictionary *)params)

+ (BOOL)requiresMainQueueSetup
{
  return YES;
}

@end
