//
//  FlutterBridgeModule.swift
//  Appspensive
//
//  Auto-generated by withFlutterBridge plugin
//

import Foundation
import React
import Flutter

@objc(FlutterBridgeModule)
class FlutterBridgeModule: NSObject {
  
  @objc
  static func requiresMainQueueSetup() -> Bool {
    return true
  }
  
  @objc
  func openFlutter(_ route: String?, params: NSDictionary?) {
    DispatchQueue.main.async {
      guard let rootViewController = self.getRootViewController() else {
        print("[FlutterBridge] Could not find root view controller")
        return
      }

      print("Running Flutter engine")
      
      let flutterEngine = FlutterEngine(name: "flutter_engine")
      
      // Set initial route when running the engine (not deprecated)
      if let route = route, !route.isEmpty {
        flutterEngine.run(withEntrypoint: nil, initialRoute: route)
      } else {
        flutterEngine.run()
      }
      
      let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
      
      rootViewController.present(flutterViewController, animated: true, completion: nil)
    }
  }
  
  private func getRootViewController() -> UIViewController? {
    guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
          let window = windowScene.windows.first,
          let rootViewController = window.rootViewController else {
      return nil
    }
    
    var topController = rootViewController
    while let presentedViewController = topController.presentedViewController {
      topController = presentedViewController
    }
    
    return topController
  }
}
