/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `/data/TransactionItem`; params?: Router.UnknownInputParams; } | { pathname: `/features/home/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/features/home/HomeViewModel`; params?: Router.UnknownInputParams; } | { pathname: `/features/home/TransactionBottomSheet`; params?: Router.UnknownInputParams; } | { pathname: `/features/settings/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/features/statistics/StatisticsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sql/AppDatabase`; params?: Router.UnknownInputParams; } | { pathname: `/sql/AppDatabaseFactory`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomBottomSheet`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomBox`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomText`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownOutputParams; } | { pathname: `/data/TransactionItem`; params?: Router.UnknownOutputParams; } | { pathname: `/features/home/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/features/home/HomeViewModel`; params?: Router.UnknownOutputParams; } | { pathname: `/features/home/TransactionBottomSheet`; params?: Router.UnknownOutputParams; } | { pathname: `/features/settings/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/features/statistics/StatisticsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/sql/AppDatabase`; params?: Router.UnknownOutputParams; } | { pathname: `/sql/AppDatabaseFactory`; params?: Router.UnknownOutputParams; } | { pathname: `/util/widgets/CustomBottomSheet`; params?: Router.UnknownOutputParams; } | { pathname: `/util/widgets/CustomBox`; params?: Router.UnknownOutputParams; } | { pathname: `/util/widgets/CustomButton`; params?: Router.UnknownOutputParams; } | { pathname: `/util/widgets/CustomText`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/statistics${`?${string}` | `#${string}` | ''}` | `/statistics${`?${string}` | `#${string}` | ''}` | `/data/TransactionItem${`?${string}` | `#${string}` | ''}` | `/features/home/HomeScreen${`?${string}` | `#${string}` | ''}` | `/features/home/HomeViewModel${`?${string}` | `#${string}` | ''}` | `/features/home/TransactionBottomSheet${`?${string}` | `#${string}` | ''}` | `/features/settings/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/features/statistics/StatisticsScreen${`?${string}` | `#${string}` | ''}` | `/sql/AppDatabase${`?${string}` | `#${string}` | ''}` | `/sql/AppDatabaseFactory${`?${string}` | `#${string}` | ''}` | `/util/widgets/CustomBottomSheet${`?${string}` | `#${string}` | ''}` | `/util/widgets/CustomBox${`?${string}` | `#${string}` | ''}` | `/util/widgets/CustomButton${`?${string}` | `#${string}` | ''}` | `/util/widgets/CustomText${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `/data/TransactionItem`; params?: Router.UnknownInputParams; } | { pathname: `/features/home/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/features/home/HomeViewModel`; params?: Router.UnknownInputParams; } | { pathname: `/features/home/TransactionBottomSheet`; params?: Router.UnknownInputParams; } | { pathname: `/features/settings/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/features/statistics/StatisticsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sql/AppDatabase`; params?: Router.UnknownInputParams; } | { pathname: `/sql/AppDatabaseFactory`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomBottomSheet`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomBox`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/util/widgets/CustomText`; params?: Router.UnknownInputParams; };
    }
  }
}
